ChainOfStores/Areas/Admin/Controllers/StorageController.cs
using ChainOfStores.DataAccess.Data;
using ChainOfStores.DataAccess.Repository.IRepository;
using ChainOfStores.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;
using System.Collections.Generic;

namespace ChainOfStores.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class StorageController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public StorageController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            List<Shop> objShopList = _unitOfWork.Shop.GetAll().ToList();
            List<Storage> objStorageList = _unitOfWork.Storage.GetAll().ToList();
            return View(objStorageList);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Storage obj)
        {
            List<Shop> shops = _unitOfWork.Shop.GetAll().ToList();
            List<Storage> storages = _unitOfWork.Storage.GetAll().ToList();
            if (ModelState.IsValid)
            {
                if (storages.Count() < shops.Count())
                {
                    _unitOfWork.Storage.Add(obj);
                    _unitOfWork.Save();
                    TempData["success"] = "Storage created successfully";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["error"] = "All shops already have storages";
                    return RedirectToAction("Index");
                    //ModelState.AddModelError("ShopId", "The all shops already have storages");
                }
            }

            return View();
        }

        public IActionResult Edit(int? id)
        {
            if (id == 0)
                return NotFound();
            Storage storageFromDb = _unitOfWork.Storage.Get(s => s.Id == id);
            if (storageFromDb == null)
                return NotFound();
            return View(storageFromDb);
        }

        [HttpPost]
        public IActionResult Edit(Storage obj)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.Storage.Update(obj);
                _unitOfWork.Save();
                TempData["success"] = "Storage updated successfully";
                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult Delete(int? id)
        {
            List<Shop> shopsFromDb = _unitOfWork.Shop.GetAll().ToList();
            if (id == 0)
                return NotFound();
            Storage storageFromDb = _unitOfWork.Storage.Get(u => u.Id == id);
            if (storageFromDb == null)
                return NotFound();
            return View(storageFromDb);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeletePost(int? id)
        {
            Storage? obj = _unitOfWork.Storage.Get(u => u.Id == id);
            if (obj == null)
                return NotFound();
            _unitOfWork.Storage.Remove(obj);
            _unitOfWork.Save();
            TempData["success"] = "Storage deleted successfully";
            return RedirectToAction("Index");
        }
    }
}

ChainOfStores/Controllers/StorageController.cs
using ChainOfStores.DataAccess.Data;
using ChainOfStores.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;
using System.Collections.Generic;

namespace ChainOfStores.Controllers
{
    public class StorageController : Controller
    {
        private readonly ApplicationDbContext _db;
        public StorageController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            List<Shop> objShopsList = _db.Shops.ToList();
            List<Storage> objStorageList= _db.Storages.ToList();
            return View(objStorageList);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Storage obj)
        {
            List<Shop> shops=_db.Shops.ToList();
            List<Storage> storages= _db.Storages.ToList();
            if(ModelState.IsValid)
            {
                if (storages.Count() < shops.Count())
                {
                    _db.Storages.Add(obj);
                    _db.SaveChanges();
                    TempData["success"] = "Storage created successfully";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["error"] = "All shops already have storages";
                    return RedirectToAction("Index");
                    //ModelState.AddModelError("ShopId", "The all shops already have storages");
                }
            }
            
            return View();
        }

        public IActionResult Edit(int? id)
        {
            if(id==0)
                return NotFound();
            Storage storageFromDb = _db.Storages.FirstOrDefault(s => s.Id==id);
            if (storageFromDb == null)
                return NotFound();
            return View(storageFromDb);
        }

        [HttpPost]
        public IActionResult Edit(Storage obj)
        {
            if (ModelState.IsValid)
            {
                _db.Storages.Update(obj);
                _db.SaveChanges();
                TempData["success"] = "Storage updated successfully";
                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult Delete(int? id)
        {
            List<Shop> shopsFromDb = _db.Shops.ToList();
            if(id==0)
                return NotFound();
            Storage storageFromDb = _db.Storages.FirstOrDefault(u=>u.Id==id);
            if(storageFromDb == null)
                return NotFound();
            return View(storageFromDb);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeletePost(int? id)
        {
            Storage? obj = _db.Storages.FirstOrDefault(u=>u.Id == id);
            if (obj == null)
                return NotFound();
            _db.Storages.Remove(obj);
            _db.SaveChanges();
            TempData["success"] = "Storage deleted successfully";
            return RedirectToAction("Index");
        }
    }
}

ChainOfStores/Areas/Admin/Views/Storage/Create.cshtml
@model Storage

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Create Storage</h2>
            <hr />
        </div>
        @*<div asp-validation-summary="ModelOnly" class="text-danger"></div>*@
        <div class="mb-3 row p-1">
            <label asp-for="PhoneNumber" class="p-0"></label>
            <input asp-for="PhoneNumber" type="text" class="form-control" />
            <span asp-validation-for="PhoneNumber" class="text-danger"></span>
        </div>
        <div class="mb-3 row p-1">
            <label asp-for="ShopId" class="p-0"></label>
            <input asp-for="ShopId" type="text" class="form-control" />
            <span asp-validation-for="ShopId" class="text-danger"></span>
        </div>
        <div class="row">
            <div class="col-6 col-md-3">
                <button type="submit" class="btn btn-primary form-control">Create</button>
            </div>
            <div class="col-6 col-md-3">
                <a asp-controller="Storage" asp-action="Index" class="btn btn-outline-secondary form-control">Back To List</a>
            </div>
        </div>
    </div>
</form>

@section Scripts{
    @{
    <partial name="_ValidationScriptsPartial"/>
    }
}

ChainOfStores/Areas/Admin/Views/Storage/Delete.cshtml
@model Storage

<form method="post">
    <input asp-for="Id" hidden />
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Delete Storage</h2>
            <hr />
        </div>
        <div class="mb-3 row p-1">
            <label asp-for="PhoneNumber" class="p-0"></label>
            <input asp-for="PhoneNumber" disabled type="text" class="form-control" />
        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Shop.Name" class="p-0"></label>
            <input asp-for="Shop.Name" disabled type="text" class="form-control" />
        </div>
        <div class="row">
            <div class="col-6 col-md-3">
                <button asp-controller="Storage" asp-action="Delete" type="submit" class="btn btn-danger form-control">Delete</button>
            </div>
            <div class="col-6 col-md-3">
                <a asp-controller="Storage" asp-action="Index" class="btn btn-outline-secondary form-control">Back To List</a>
            </div>
        </div>
    </div>
</form>

ChainOfStores/Areas/Admin/Views/Storage/Edit.cshtml
@model Storage

<form method="post">
    @* Ներքևի տողը պետք է լինում երբ խնդիր է առաջանում կապված նրա հետ,որ այս Edit view-ի մեջ Id-ի համար լրացված դաշտ չկա*@
    <input asp-for="Id" hidden />
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Edit Storage</h2>
            <hr />
        </div>
        @*<div asp-validation-summary="ModelOnly" class="text-danger"></div>*@
        <div class="mb-3 row p-1">
            <label asp-for="PhoneNumber" class="p-0"></label>
            <input asp-for="PhoneNumber" type="text" class="form-control" />
            <span asp-validation-for="PhoneNumber" class="text-danger"></span>
        </div>
        <div class="mb-3 row p-1">
            <label asp-for="ShopId" class="p-0"></label>
            <input asp-for="ShopId" type="text" class="form-control" />
            <span asp-validation-for="ShopId" class="text-danger"></span>
        </div>
        <div class="row">
            <div class="col-6 col-md-3">
                <button type="submit" class="btn btn-primary form-control">Update</button>
            </div>
            <div class="col-6 col-md-3">
                <a asp-controller="Storage" asp-action="Index" class="btn btn-outline-secondary form-control">Back To List</a>
            </div>
        </div>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

ChainOfStores/Areas/Admin/Views/Storage/Index.cshtml
@model IEnumerable<Storage>

<div class="card shadow border-0 mt-4">
    <div class="card-header bg-secondary bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h1 class="text-white py-2">Storage's List</h1>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <div class="row pb-3">
            <div class="col-6">
            </div>
            <div class="col-6 text-end">
                <a asp-controller="Storage" asp-action="Create" class="btn btn-primary"><i class="bi bi-plus-circle"></i>Create New Storage</a>
            </div>
        </div>
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Phone Number</th>
                    <th>Storage of Shop</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var obj in Model)
                {
                    <tr>
                        <td>@obj.PhoneNumber</td>
                        <td>@obj.Shop.Name</td>
                        <td>
                            <div class="w-75 btn-group" role="group">
                                <a asp-controller="Storage" asp-action="Edit" asp-route-id="@obj.Id" class="btn btn-primary mx-2"><i class="bi bi-pencil-square"></i>Edit</a>
                                <a asp-controller="Storage" asp-action="Delete" asp-route-id="@obj.Id" class="btn btn-danger mx-2"><i class="bi bi-trash3"></i>Delete</a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>