ChainOfStores/Controllers/BakeryController.cs
using ChainOfStores.DataAccess.Data;
using ChainOfStores.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;

namespace ChainOfStores.Controllers
{
    public class BakeryController : Controller
    {
        private readonly ApplicationDbContext _db;
     
        public BakeryController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            List<Shop> objShopsList = _db.Shops.ToList();
            List<Bakery> objBakeryList=_db.Bakeries.ToList();
            return View(objBakeryList);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Bakery obj)
        {
            List<Shop> shops = _db.Shops.ToList();
            List<Bakery> bakeries = _db.Bakeries.ToList();
            if (ModelState.IsValid)
            {
                if (bakeries.Count() < shops.Count())
                {
                    _db.Bakeries.Add(obj);
                    _db.SaveChanges();
                    TempData["success"] = "Bakery created successfully";
                    return RedirectToAction("Index");
                }
                else
                {
                    //ModelState.AddModelError("ShopId", "The all shops already have bakeries");
                    TempData["error"] = "All shops already have bakeries";
                    return RedirectToAction("Index");
                }
            }

            return View();
        }

        public IActionResult Edit(int? id)
        {
            if (id==0)
                return NotFound();
            Bakery bakeryFromDb = _db.Bakeries.FirstOrDefault(b => b.Id == id);
            if (bakeryFromDb==null)
                return NotFound();
            return View(bakeryFromDb);
        }

        [HttpPost]
        public ActionResult Edit(Bakery obj)
        {
            if (ModelState.IsValid)
            {
                _db.Bakeries.Update(obj);
                _db.SaveChanges();
                TempData["success"] = "Bakery updated successfully";
                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult Delete(int? id)
        {
            List<Shop> shopsFromDb = _db.Shops.ToList();
            if(id == 0)
                return NotFound();
            Bakery bakeryFromDb = _db.Bakeries.FirstOrDefault(u=>u.Id == id);
            if(bakeryFromDb==null)
                return NotFound();
            return View(bakeryFromDb);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeletePost(int? id)
        {
            Bakery? obj = _db.Bakeries.FirstOrDefault(u=>u.Id==id);
            if (obj==null)
                return NotFound();
            _db.Bakeries.Remove(obj);
            _db.SaveChanges();
            TempData["success"] = "Bakery deleted successfully";
            return RedirectToAction("Index");
        }
    }
}

ChainOfStores/Controllers/RoleController.cs
using ChainOfStores.DataAccess.Data;
using ChainOfStores.Models;
using Microsoft.AspNetCore.Mvc;

namespace ChainOfStores.Controllers
{
    public class RoleController : Controller
    {
        private readonly ApplicationDbContext _db;
        public RoleController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            List<Role> objRoleList = _db.Roles.ToList();
            return View(objRoleList);
        }

        public IActionResult Create() 
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Role obj) 
        {
            if(ModelState.IsValid)
            {
                _db.Roles.Add(obj);
                _db.SaveChanges();
                TempData["success"] = "Role created successfully";
                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult Edit(int? id)
        {
            if(id == 0)
                return NotFound();
            Role roleFromDb = _db.Roles.FirstOrDefault(x => x.Id == id);
            if(roleFromDb == null)
                return NotFound();
            return View(roleFromDb);
        }

        [HttpPost]
        public IActionResult Edit(Role obj) 
        {
            if(ModelState.IsValid)
            {
                _db.Roles.Update(obj);
                _db.SaveChanges();
                TempData["success"] = "Role updated successfully";
                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult Delete(int? id)
        {
            if (id == 0)
                return NotFound();
            Role roleFromDb = _db.Roles.FirstOrDefault(u=>u.Id == id);
            if (roleFromDb == null)
                return NotFound();
            return View(roleFromDb);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeletePost(int? id)
        {
            Role? obj = _db.Roles.FirstOrDefault(u=> u.Id == id);
            if(obj == null)
                return NotFound();
            _db.Roles.Remove(obj);
            _db.SaveChanges();
            TempData["success"] = "Role deleted successfully";
            return RedirectToAction("Index");
        }

    }
}

ChainOfStores/Controllers/SalaryController.cs
using ChainOfStores.DataAccess.Data;
using ChainOfStores.Models;
using Microsoft.AspNetCore.Mvc;

namespace ChainOfStores.Controllers
{
    public class SalaryController : Controller
    {
        private readonly ApplicationDbContext _db;
        public SalaryController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            List<Salary> objSalaryList = _db.Salaries.ToList();
            return View(objSalaryList);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Salary obj)
        {
            if(ModelState.IsValid)
            {
                _db.Salaries.Add(obj);
                _db.SaveChanges();
                TempData["success"] = "Salary created successfully";
                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult Edit(int? id)
        {
            if(id==0)
                return NotFound();
            Salary salaryFromDb = _db.Salaries.FirstOrDefault(s => s.Id == id);
            if(salaryFromDb==null)
                return NotFound();
            return View(salaryFromDb);
        }

        [HttpPost]
        public IActionResult Edit(Salary obj)
        {
            if(ModelState.IsValid)
            {
                _db.Salaries.Update(obj);
                _db.SaveChanges();
                TempData["success"] = "Salary updated successfully";
                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult Delete(int? id)
        {
            if (id==0)
                return NotFound();
            Salary salaryFromDb = _db.Salaries.FirstOrDefault(u=>u.Id==id);
            if(salaryFromDb==null)
                return NotFound();
            return View(salaryFromDb);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeletePost (int? id)
        {
            Salary? obj = _db.Salaries.FirstOrDefault(u=>u.Id == id);
            if (obj==null)
                return NotFound();
            _db.Salaries.Remove(obj);
            _db.SaveChanges();
            TempData["success"] = "Salary deleted successfully";
            return RedirectToAction("Index");
        }
    }
}

ChainOfStores/Controllers/ShopController.cs
using ChainOfStores.DataAccess.Data;
using ChainOfStores.Models;
using Microsoft.AspNetCore.Mvc;

namespace ChainOfStores.Controllers
{
    public class ShopController : Controller
    {
        private readonly ApplicationDbContext _db;
        public ShopController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            List<Shop> objShopsList=_db.Shops.ToList();
            return View(objShopsList);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Shop obj)
        {
            if (ModelState.IsValid)
            {
                _db.Shops.Add(obj);
                _db.SaveChanges();
                TempData["success"] = "Shop created successfully";
                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult Edit(int? id)
        {
            if(id==0)
                return NotFound();
            Shop shopFromDb = _db.Shops.FirstOrDefault(x => x.Id == id);
            if(shopFromDb == null)
                return NotFound();
            return View(shopFromDb);
        }

        [HttpPost]
        public IActionResult Edit(Shop obj)
        {
            if (ModelState.IsValid)
            {
                _db.Shops.Update(obj);
                _db.SaveChanges();
                TempData["success"] = "Shop updated successfully";
                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult Delete(int? id)
        {
            if (id == 0) 
                return NotFound(); 
            Shop shopFromDb = _db.Shops.FirstOrDefault(u=>u.Id==id);
            if(shopFromDb == null)
                return NotFound();
            return View(shopFromDb);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeletePost(int? id)
        {
            Shop? obj = _db.Shops.FirstOrDefault(s=>s.Id==id);
            if (obj == null)
                return NotFound();
            _db.Shops.Remove(obj);
            _db.SaveChanges();
            TempData["success"] = "Shop deleted successfully";
            return RedirectToAction("Index");
        }
    }
}

ChainOfStores/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ChainOfStores</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ChainOfStores.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="Customer" asp-controller="Home" asp-action="Index">ChainOfStores</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Customer" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <div class="dropdown">
                            <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Chain
                            </button>
                            <ul class="dropdown-menu">
                                <li>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Employee" asp-action="Index">Employee</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Shop" asp-action="Index">Shop</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Bakery" asp-action="Index">Bakery</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Storage" asp-action="Index">Storage</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Salary" asp-action="Index">Salary</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Role" asp-action="Index">Role</a>
                                </li>
                            </ul>
                        </div>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification"></partial>
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ChainOfStores - <a asp-area="Customer" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ChainOfStores/Views/Shared/_Notification.cshtml
@if(TempData["success"]!=null){
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>

    <script type="text/javascript">
        toastr.success('@TempData["success"]')
    </script>
}
@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>

    <script type="text/javascript">
        toastr.error('@TempData["error"]')
    </script>
}