ChainOfStores/Areas/Admin/Controllers/EmployeeController.cs
using ChainOfStores.DataAccess.Data;
using ChainOfStores.DataAccess.Repository.IRepository;
using ChainOfStores.Models;
using ChainOfStores.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Data;
using System.Xml.Linq;

namespace ChainOfStores.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class EmployeeController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public EmployeeController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _webHostEnvironment = webHostEnvironment;
        }
        public IActionResult Index()
        {
            //List<Role> roles = _unitOfWork.Role.GetAll().ToList();
            //List<Salary> salaries = _unitOfWork.Salary.GetAll().ToList();
            //List<Employee> EmployeeList = _unitOfWork.Employee.GetAll().ToList();
            //foreach(var Employee in EmployeeList)
            //{
            //    for(int i = 1; i <= salaries.Count; i++)
            //    {
            //        if(Employee.SalaryId == i)
            //        {
            //            if (Employee.Role.Name=="Manager")
            //            {
            //                int seniority = DateTime.Now.Year - Employee.DateOfEmployment.Year;
            //                Employee.SalaryId = seniority * 15 + salaries[i-1].BaseSalary;
            //            }
            //            else
            //            {
            //                int seniority = DateTime.Now.Year - Employee.DateOfEmployment.Year;
            //                Employee.SalaryId = seniority * 10 + salaries[i - 1].BaseSalary;
            //            }
            //        }
            //    }
            //}
     
            List<Employee> objEmployeeList = _unitOfWork.Employee.GetAll(includeProperties:"Salary,Role").ToList();
            return View(objEmployeeList);
        }

        public IActionResult Upsert(int? id)
        {
            EmployeeVM employeeVM = new()
            {
                SalaryList = _unitOfWork.Salary.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString(),
                }),
                RoleList = _unitOfWork.Role.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString(),
                }),
                ShopList = _unitOfWork.Shop.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString(),
                }),
                StorageList = _unitOfWork.Storage.GetAll().Select(u => new SelectListItem
                {
                    Text = u.PhoneNumber,
                    Value = u.Id.ToString(),
                }),
                BakeryList = _unitOfWork.Bakery.GetAll().Select(u => new SelectListItem
                {
                    Text = u.PhoneNumber,
                    Value = u.Id.ToString(),
                }),

                Employee = new Employee()
            };
            if (id == null || id == 0)
            {
                //Create
                return View(employeeVM);
            }
            else
            {
                //Update
                employeeVM.Employee = _unitOfWork.Employee.Get(u => u.Id == id);
                return View(employeeVM);
            }
        }

        [HttpPost]
        public IActionResult Upsert(EmployeeVM employeeVM, IFormFile? file)
        {
            if (ModelState.IsValid)
            {
                string wwwRootPath = _webHostEnvironment.WebRootPath;
                if (file != null)
                {
                    string fileName = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);
                    string employeePath = Path.Combine(wwwRootPath, @"images\employee");

                    if (!string.IsNullOrEmpty(employeeVM.Employee.ImageURL))
                    {    //delete the old image
                        var oldImagePath = Path.Combine(wwwRootPath, employeeVM.Employee.ImageURL.TrimStart('\\'));

                        if (System.IO.File.Exists(oldImagePath))
                        {
                            System.IO.File.Delete(oldImagePath);
                        }
                    }

                    using (var fileStream = new FileStream(Path.Combine(employeePath, fileName), FileMode.Create))
                    {
                        file.CopyTo(fileStream);
                    }
                    employeeVM.Employee.ImageURL = @"\images\employee\" + fileName;
                }
                
                if (employeeVM.Employee.Id == 0)
                {
                    _unitOfWork.Employee.Add(employeeVM.Employee);
                }
                else
                {
                    _unitOfWork.Employee.Update(employeeVM.Employee);
                }
                _unitOfWork.Save();
                if (employeeVM.Employee.Id == 0)
                    TempData["success"] = "Employee added successfully";
                else
                    TempData["success"] = "Employee updated successfully";
                return RedirectToAction("Index");
            }
            else
            {
                employeeVM.SalaryList = _unitOfWork.Salary.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString(),
                });
                employeeVM.RoleList = _unitOfWork.Role.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString(),
                });
                employeeVM.ShopList = _unitOfWork.Shop.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString(),
                });
                employeeVM.StorageList = _unitOfWork.Shop.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString(),
                });
                employeeVM.BakeryList = _unitOfWork.Shop.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString(),
                });
                return View(employeeVM);
            }
        }

        #region API CALLS

        [HttpGet]
        public IActionResult GetAll()
        {
            List<Employee> objEmployeeList = _unitOfWork.Employee.GetAll(includeProperties: "Salary,Role").ToList();
            List<Role> roles = _unitOfWork.Role.GetAll().ToList();
            List<Salary> salaries = _unitOfWork.Salary.GetAll().ToList();
            
            foreach (var Employee in objEmployeeList)
            {
                for (int i = 1; i <= salaries.Count; i++)
                {
                    if (Employee.SalaryId == i)
                    {
                        if (Employee.RoleId == 1)
                        {
                            int seniority = DateTime.Now.Year - Employee.DateOfEmployment.Year;
                            Employee.SalaryId = seniority * 15 + salaries[i - 1].BaseSalary;
                        }
                        else
                        {
                            int seniority = DateTime.Now.Year - Employee.DateOfEmployment.Year;
                            Employee.SalaryId = seniority * 10 + salaries[i - 1].BaseSalary;
                        }
                    }
                }
            }
            
            return Json(new { data = objEmployeeList });
        }

        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            var employeeToBeDeleted = _unitOfWork.Employee.Get(u => u.Id == id);
            if (employeeToBeDeleted == null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }
            var oldImagePath = Path.Combine(_webHostEnvironment.WebRootPath, employeeToBeDeleted.ImageURL.TrimStart('\\'));

            if (System.IO.File.Exists(oldImagePath))
            {
                System.IO.File.Delete(oldImagePath);
            }

            _unitOfWork.Employee.Remove(employeeToBeDeleted);
            _unitOfWork.Save();

            return Json(new { success = true, message = "Delete Successful" });
        }

        #endregion
    }
}

ChainOfStores/Controllers/EmployeeController.cs
using ChainOfStores.DataAccess.Data;
using ChainOfStores.DataAccess.Repository.IRepository;
using ChainOfStores.Models;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using System.Xml.Linq;

namespace ChainOfStores.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public EmployeeController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            List<Employee> objEmployeeList = _unitOfWork.Employee.GetAll().ToList();
            return View(objEmployeeList);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Employee obj)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.Employee.Add(obj);
                _unitOfWork.Save();
                TempData["success"] = "Employee added successfully";
                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult Edit(int? id)
        {
            if (id == 0)
                return NotFound();
            Employee employeeFromDb = _unitOfWork.Employee.Get(x => x.Id == id);
            if (employeeFromDb == null)
                return NotFound();
            return View(employeeFromDb);
        }

        [HttpPost]
        public IActionResult Edit(Employee obj)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.Employee.Update(obj);
                _unitOfWork.Save();
                TempData["success"] = "Employee updated successfully";
                return RedirectToAction("Index");
            }
            return View();

        }

        public IActionResult Delete(int? id)
        {
            if(id == 0)
                return NotFound();
            Employee employeeFromDb = _unitOfWork.Employee.Get(u=>u.Id == id);
            if(employeeFromDb == null)
                return NotFound();
            return View(employeeFromDb);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeletePost(int? id)
        {
            Employee? obj = _unitOfWork.Employee.Get(u=> u.Id == id);
            if(obj == null)
                return NotFound();
            _unitOfWork.Employee.Remove(obj);
            _unitOfWork.Save();
            TempData["success"] = "Employee deleted successfully";
            return RedirectToAction("Index");
        }
    }
}

ChainOfStores/Areas/Admin/Views/Employee/Index.cshtml
@model List<Employee>

<div class="card shadow border-0 my-4">
    <div class="card-header bg-secondary bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h1 class="text-white py-2">Employees</h1>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <div class="row pb-3">
            <div class="col-6">
            </div>
            <div class="col-6 text-end">
                <a asp-controller="Employee" asp-action="Upsert" class="btn btn-primary"><i class="bi bi-plus-circle"></i>Add New Employee</a>
            </div>
        </div>
        <table id="tblData" class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Phone Number</th>
                    <th>Date of Employment</th>
                    <th>Shop</th>
                    <th>Storage</th>
                    <th>Bakery</th>
                    <th>Salary in $</th>
                    <th>Role</th>
                    <th></th>
                </tr>
            </thead>
        </table>
    </div>
</div>

@section Scripts{
    <script src="~/js/product.js"></script>
}

ChainOfStores/Areas/Admin/Views/Employee/Upsert.cshtml
@model EmployeeVM

<div class="card shadow border-0 my-4">
    <div class="card-header bg-secondary bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h1 class="text-white py-2">@(Model.Employee.Id != 0 ? "Update" : "Add") Employee</h1>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <form method="post" class="row" enctype="multipart/form-data">
            <input asp-for="Employee.Id" hidden />
            <input asp-for="Employee.ImageURL" hidden />
            <div class="row">
                <div class="col-10">
                    <div class="border p-3">
                        @*<div asp-validation-summary="ModelOnly" class="text-danger"></div>*@
                        <div class="form-floating py-2 col-12">
                            <input asp-for="Employee.FirstName" class="form-control border-0 shadow" />
                            <label asp-for="Employee.FirstName" class="ms-2"></label>
                            <span asp-validation-for="Employee.FirstName" class="text-danger"></span>
                        </div>
                        <div class="form-floating py-2 col-12">
                            <input asp-for="Employee.LastName" class="form-control border-0 shadow" />
                            <label asp-for="Employee.LastName" class="ms-2"></label>
                            <span asp-validation-for="Employee.LastName" class="text-danger"></span>
                        </div>
                        <div class="form-floating py-2 col-12">
                            <input asp-for="Employee.PhoneNumber" class="form-control border-0 shadow" />
                            <label asp-for="Employee.PhoneNumber" class="ms-2"></label>
                            <span asp-validation-for="Employee.PhoneNumber" class="text-danger"></span>
                        </div>
                        <div class="form-floating py-2 col-12">
                            <input asp-for="Employee.DateOfEmployment" class="form-control border-0 shadow" />
                            <label asp-for="Employee.DateOfEmployment" class="ms-2"></label>
                            <span asp-validation-for="Employee.DateOfEmployment" class="text-danger"></span>
                        </div>

                        <div class="form-floating py-2 col-12">
                            <select asp-for="@Model.Employee.SalaryId" asp-items="@Model.SalaryList" class="form-select border-0 shadow">
                                <option disabled selected>--Select Salary--</option>
                            </select>
                            <label asp-for="Employee.SalaryId" class="ms-2"></label>
                            <span asp-validation-for="Employee.SalaryId" class="text-danger"></span>
                        </div>
                        <div class="form-floating py-2 col-12">
                            <select asp-for="@Model.Employee.RoleId" asp-items="@Model.RoleList" class="form-select border-0 shadow">
                                <option disabled selected>--Select Role--</option>
                            </select>
                            <label asp-for="Employee.RoleId" class="ms-2"></label>
                            <span asp-validation-for="Employee.RoleId" class="text-danger"></span>
                        </div>
                        <div class="form-floating py-2 col-12">
                            <select asp-for="@Model.Employee.ShopId" asp-items="@Model.ShopList" class="form-select border-0 shadow">
                                <option disabled selected>--Select Shop--</option>
                            </select>
                            <label asp-for="Employee.ShopId" class="ms-2"></label>
                            <span asp-validation-for="Employee.ShopId" class="text-danger"></span>
                        </div>
                        <div class="form-floating py-2 col-12">
                            <select asp-for="@Model.Employee.StorageId" asp-items="@Model.StorageList" class="form-select border-0 shadow">
                                <option disabled selected>--Select Storage--</option>
                            </select>
                            <label asp-for="Employee.StorageId" class="ms-2"></label>
                            <span asp-validation-for="Employee.StorageId" class="text-danger"></span>
                        </div>
                        <div class="form-floating py-2 col-12">
                            <select asp-for="@Model.Employee.BakeryId" asp-items="@Model.BakeryList" class="form-select border-0 shadow">
                                <option disabled selected>--Select Bakery--</option>
                            </select>
                            <label asp-for="Employee.BakeryId" class="ms-2"></label>
                            <span asp-validation-for="Employee.BakeryId" class="text-danger"></span>
                        </div>
                        <div class="form-floating py-2 col-12">
                            <input type="file" name="file" class="form-control border-0 shadow" />
                            <label asp-for="Employee.ImageURL" class="ms-2"></label>
                        </div>
                        <div class="row pt-2">
                            <div class="col-6 col-md-3">
                                @if (Model.Employee.Id != 0)
                                {
                                    <button type="submit" class="btn btn-primary form-control">Update</button>
                                }
                                else
                                {
                                    <button type="submit" class="btn btn-primary form-control">Create</button>
                                }
                            </div>
                            <div class="col-6 col-md-3">
                                <a asp-controller="Employee" asp-action="Index" class="btn btn-outline-primary form-control">Back To List</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-2">
                    <img src="@Model.Employee.ImageURL" width="100%" style="border-radius:5px; border:1px solid #bbb9b9" />
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts{
    @{
        <partian name="_ValidationScriptsPartial" />
    }
}